'use client';

import { useEffect, useState } from 'react';
import { ArrowRight, CircleAlert, Plus, UsersRound } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';

type Client = { id: string; name: string; company: string | null; email: string | null; phone: string | null };
const examples = [
  { id: 'aurora-studio', name: 'Aurora Studio', company: 'Arquitetura & interiores', email: 'contato@aurorastudio.com.br', phone: null },
  { id: 'nexo-tecnologia', name: 'Nexo Tecnologia', company: 'SaaS B2B', email: null, phone: null },
  { id: 'casa-oliva', name: 'Casa Oliva', company: 'Gastronomia', email: null, phone: null },
];

export function ClientsView() {
  const [items, setItems] = useState<Client[]>(examples);
  const [open, setOpen] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => { void (async () => { const response = await fetch('/api/clients'); const body = await response.json() as { data?: Client[] }; if (response.ok && body.data?.length) setItems(body.data); if (new URLSearchParams(location.search).get('novo') === '1') setOpen(true); })(); }, []);
  async function create(form: FormData) { setError(''); const response = await fetch('/api/clients', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(Object.fromEntries(form)) }); const body = await response.json() as { data?: Client; error?: string }; if (!response.ok) setError(body.error ?? 'Não foi possível cadastrar o cliente.'); else if (body.data) { setItems((current) => [body.data!, ...current.filter((item) => !examples.some((example) => example.id === item.id))]); setOpen(false); history.replaceState(null, '', '/clientes'); } }
  return <>{error && <div className="mb-4 flex items-center gap-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700"><CircleAlert className="size-4" />{error}</div>}<div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><span className="rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-xs font-bold text-amber-900">Todos · {items.length}</span><span className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-500">Ativos</span></div><button onClick={() => setOpen(true)} className="flex h-10 items-center gap-2 rounded-xl bg-amber-400 px-4 text-sm font-bold text-slate-950"><Plus className="size-4" /> Novo cliente</button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map((client) => <a key={client.id} href={`/clientes/${client.id}`} className="group rounded-2xl border border-slate-200 bg-white p-5 transition hover:border-amber-300 hover:shadow-md"><div className="flex items-start gap-3"><span className="grid size-11 place-items-center rounded-xl bg-amber-100 font-black text-amber-900">{client.name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</span><div className="min-w-0 flex-1"><h2 className="font-bold">{client.name}</h2><p className="mt-1 text-xs text-slate-500">{client.company || 'Cliente'}</p></div><ArrowRight className="size-4 text-slate-300 group-hover:text-amber-600" /></div><div className="mt-5 border-t pt-4 text-xs text-slate-500">{client.email || client.phone || 'Cadastro ativo'}</div></a>)}</div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Novo cliente</DialogTitle><DialogDescription>Cadastre as informações principais para iniciar o atendimento.</DialogDescription></DialogHeader><form onSubmit={(event) => { event.preventDefault(); void create(new FormData(event.currentTarget)); }} className="space-y-4"><label className="block text-sm font-semibold">Nome<input name="name" required minLength={2} className="mt-1.5 h-10 w-full rounded-xl border px-3 font-normal" /></label><label className="block text-sm font-semibold">Empresa ou segmento<input name="company" className="mt-1.5 h-10 w-full rounded-xl border px-3 font-normal" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">E-mail<input name="email" type="email" className="mt-1.5 h-10 w-full rounded-xl border px-3 font-normal" /></label><label className="block text-sm font-semibold">Telefone<input name="phone" className="mt-1.5 h-10 w-full rounded-xl border px-3 font-normal" /></label></div><DialogFooter><button type="button" onClick={() => setOpen(false)} className="h-10 rounded-xl border px-4 text-sm font-semibold">Cancelar</button><button type="submit" className="h-10 rounded-xl bg-amber-400 px-4 text-sm font-bold text-slate-950"><UsersRound className="mr-2 inline size-4" />Cadastrar cliente</button></DialogFooter></form></DialogContent></Dialog></>;
}
