import { ArrowLeft, AtSign, CheckCircle2, Clock3, ExternalLink, FolderKanban, Link2, Mail, MessageSquare, Phone, Plus, UserRound } from 'lucide-react';

const tabs = [
  { label: 'Visão geral', href: null },
  { label: 'Briefings', href: '/entradas' },
  { label: 'Tarefas', href: '/tarefas' },
  { label: 'Design', href: '/entradas?setor=designer' },
  { label: 'Social Media', href: '/entradas?setor=social_media' },
  { label: 'Tráfego', href: '/entradas?setor=trafego' },
  { label: 'Web', href: '/entradas?setor=web' },
  { label: 'Arquivos', href: null },
  { label: 'Comentários', href: null },
  { label: 'Histórico', href: null },
];

export function ClientWorkspaceView() {
  return <div>
    <a href="/clientes" className="mb-4 inline-flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-amber-700"><ArrowLeft className="size-3.5" /> Voltar para clientes</a>
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-col gap-5 sm:flex-row sm:items-start"><span className="grid size-16 place-items-center rounded-2xl bg-gradient-to-br from-amber-400 to-yellow-300 text-base font-bold text-white">AS</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold">Aurora Studio</h2><span className="rounded-lg bg-emerald-50 px-2 py-1 text-[10px] font-semibold text-emerald-600">Ativo</span></div><p className="mt-1 text-xs text-slate-400">Arquitetura & interiores · Cliente desde 12/03/2025</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-[11px] text-slate-500"><span className="flex items-center gap-1.5"><Mail className="size-3.5" /> contato@aurorastudio.com.br</span><span className="flex items-center gap-1.5"><Phone className="size-3.5" /> (11) 98765-4321</span><span className="flex items-center gap-1.5"><AtSign className="size-3.5" /> @aurorastudio</span></div></div><button className="flex h-9 items-center gap-2 rounded-xl bg-amber-400 px-3 text-xs font-semibold text-slate-950"><Plus className="size-4" /> Nova solicitação</button></div></section>

    <div className="mt-4 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><nav className="flex min-w-max px-3">{tabs.map((tab, index) => tab.href ? <a key={tab.label} href={tab.href} className="border-b-2 border-transparent px-3 py-3.5 text-[11px] font-semibold text-slate-400 hover:text-slate-700">{tab.label}</a> : <button key={tab.label} className={`border-b-2 px-3 py-3.5 text-[11px] font-semibold ${index === 0 ? 'border-amber-500 text-amber-700' : 'border-transparent text-slate-400'}`}>{tab.label}</button>)}</nav></div>

    <div className="mt-4 grid gap-4 xl:grid-cols-[1.35fr_.65fr]">
      <div className="space-y-4"><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><h3 className="text-sm font-bold">Projetos ativos</h3><p className="text-[10px] text-slate-400">Visão de progresso da conta</p></div><button className="text-xs font-semibold text-amber-700">Ver todos</button></div><div className="mt-4 space-y-3">{[{ name: 'Campanha de primavera', progress: 68, tasks: '8 de 12', due: '12 set', color: 'bg-amber-400' }, { name: 'Redes sociais', progress: 76, tasks: '19 de 25', due: 'Contínuo', color: 'bg-sky-500' }, { name: 'Google Ads', progress: 54, tasks: '7 de 13', due: '30 set', color: 'bg-amber-500' }].map((project) => <div key={project.name} className="rounded-xl border border-slate-100 p-4"><div className="flex items-center gap-3"><span className={`grid size-8 place-items-center rounded-lg text-white ${project.color}`}><FolderKanban className="size-4" /></span><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><p className="text-xs font-semibold">{project.name}</p><p className="text-[10px] text-slate-400">{project.tasks}</p></div><div className="mt-2 h-1.5 rounded-full bg-slate-100"><div className={`h-full rounded-full ${project.color}`} style={{ width: `${project.progress}%` }} /></div></div><span className="text-[10px] text-slate-400">{project.due}</span></div></div>)}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><h3 className="text-sm font-bold">Tarefas recentes</h3><p className="text-[10px] text-slate-400">Produção atual da conta</p></div><a href="/tarefas" className="text-xs font-semibold text-amber-700">Abrir tarefas</a></div><div className="mt-4 divide-y">{[{ title: 'Campanha de primavera', status: 'Em produção', tone: 'bg-amber-50 text-amber-700', owner: 'ML', due: 'Hoje, 16:00' }, { title: 'Roteiro Reels — bastidores', status: 'Aguardando aprovação', tone: 'bg-amber-50 text-amber-600', owner: 'AM', due: 'Amanhã' }, { title: 'Atualizar página de projetos', status: 'A fazer', tone: 'bg-slate-100 text-slate-500', owner: 'RS', due: '05 set' }].map((task) => <div key={task.title} className="flex flex-wrap items-center gap-3 py-3"><CheckCircle2 className="size-4 text-slate-300" /><div className="min-w-[180px] flex-1"><p className="text-xs font-semibold">{task.title}</p><p className="mt-0.5 flex items-center gap-1 text-[10px] text-slate-400"><Clock3 className="size-3" />{task.due}</p></div><span className={`rounded-lg px-2 py-1 text-[9px] font-semibold ${task.tone}`}>{task.status}</span><span className="grid size-7 place-items-center rounded-full bg-slate-900 text-[8px] font-bold text-white">{task.owner}</span></div>)}</div></section></div>

      <aside className="space-y-4"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-sm font-bold">Responsável pela conta</h3><div className="mt-4 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-emerald-100 text-xs font-bold text-emerald-700">AM</span><div><p className="text-xs font-semibold">Ana Martins</p><p className="text-[10px] text-slate-400">Social Media</p></div></div><div className="mt-4 grid grid-cols-2 gap-2"><SmallStat label="Abertas" value="12" /><SmallStat label="Atrasadas" value="1" /></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-sm font-bold">Links rápidos</h3><div className="mt-3 space-y-2"><QuickLink icon={ExternalLink} label="Site do cliente" /><QuickLink icon={AtSign} label="Instagram" /><QuickLink icon={Link2} label="Pasta no Drive" /></div></section><section className="rounded-2xl bg-[#181818] p-5 text-white"><div className="flex items-center justify-between"><div><h3 className="text-sm font-bold">Atividade</h3><p className="text-[10px] text-slate-400">Últimas 24 horas</p></div><MessageSquare className="size-4 text-amber-300" /></div><div className="mt-4 space-y-4 text-[10px] text-slate-400"><p><strong className="text-white">Marina</strong> enviou uma peça para aprovação.<br /><span>há 28 min</span></p><p><strong className="text-white">Ana</strong> criou o briefing “Roteiro Reels”.<br /><span>há 2 h</span></p><p><strong className="text-white">Rafael</strong> concluiu uma alteração no site.<br /><span>há 5 h</span></p></div></section></aside>
    </div>
  </div>;
}

function SmallStat({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[9px] uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div>; }
function QuickLink({ icon: Icon, label }: { icon: typeof UserRound; label: string }) { return <button className="flex w-full items-center gap-2 rounded-lg p-2 text-left text-[11px] font-medium text-slate-600 hover:bg-slate-50"><Icon className="size-3.5 text-slate-400" />{label}<ExternalLink className="ml-auto size-3 text-slate-300" /></button>; }
