'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, CalendarCheck2, CircleAlert, ExternalLink, Save, UserRound } from 'lucide-react';
import { platformOptions, resultOptions, type PlatformKey, type ResultStatus } from '@/lib/operations';

type Profile = { id: string; name: string; company: string | null; email: string | null; phone: string | null; website: string | null; instagram: string | null; joinedAt: string | null; status: string; statusColor: string; tier: string; analystName: string | null; managerNames: string[]; resultStatus: ResultStatus; platforms: PlatformKey[]; dailyBudgetCents: number | null; intakeFormUrl: string | null; operationNotes: string | null; googleCheckedAt: string | null; metaCheckedAt: string | null; socialCheckedAt: string | null };

export function ClientProfileView({ clientId }: { clientId: string }) {
  const [profile, setProfile] = useState<Profile | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(false);
  useEffect(() => { void (async () => { const response = await fetch(`/api/client-profile?id=${encodeURIComponent(clientId)}`); const body = await response.json() as { data?: Profile; error?: string }; if (!response.ok) setError(body.error ?? 'Não foi possível abrir o cliente.'); else setProfile(body.data ?? null); setLoading(false); })(); }, [clientId]);
  function change(patch: Partial<Profile>) { setProfile((current) => current ? { ...current, ...patch } : current); }
  async function save() { if (!profile) return; setSaving(true); setError(''); setSuccess(false); const response = await fetch('/api/client-profile', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ clientId: profile.id, tier: profile.tier, analystName: profile.analystName, managerNames: profile.managerNames, resultStatus: profile.resultStatus, platforms: profile.platforms, dailyBudget: profile.dailyBudgetCents == null ? null : profile.dailyBudgetCents / 100, intakeFormUrl: profile.intakeFormUrl, operationNotes: profile.operationNotes, googleCheckedAt: profile.googleCheckedAt, metaCheckedAt: profile.metaCheckedAt, socialCheckedAt: profile.socialCheckedAt }) }); const body = await response.json() as { error?: string }; if (!response.ok) setError(body.error ?? 'Não foi possível salvar a ficha.'); else { setSuccess(true); window.setTimeout(() => setSuccess(false), 2200); } setSaving(false); }
  if (loading) return <div className="rounded-2xl border bg-white p-10 text-center text-sm text-slate-500">Carregando ficha do cliente…</div>;
  if (!profile) return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-rose-700"><CircleAlert className="mb-2 size-5" />{error || 'Cliente não encontrado.'}</div>;
  const initials = profile.name.split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase();
  return <div className="space-y-5"><Link href="/clientes" className="inline-flex items-center gap-1.5 text-sm font-semibold text-slate-500 hover:text-amber-700"><ArrowLeft className="size-4" /> Voltar para clientes</Link>
    {error && <div className="flex items-center gap-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700"><CircleAlert className="size-4" />{error}</div>}
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="h-2 bg-amber-400" /><div className="p-5 sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-start"><div className="grid size-16 shrink-0 place-items-center rounded-2xl bg-[#181818] text-xl font-black text-amber-300">{initials}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-black">{profile.name}</h2><span className="rounded-lg px-2.5 py-1 text-xs font-bold text-white" style={{ backgroundColor: profile.statusColor }}>{profile.status}</span><input aria-label="Plano" value={profile.tier} onChange={(event) => change({ tier: event.target.value })} className="h-8 w-24 rounded-lg border border-slate-200 px-2 text-xs font-bold" /></div><p className="mt-1 text-sm text-slate-500">Segmento: {profile.company || 'Não informado'}</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm text-slate-500">{profile.email && <span>{profile.email}</span>}{profile.phone && <span>{profile.phone}</span>}{profile.joinedAt && <span>Entrada: {new Intl.DateTimeFormat('pt-BR', { timeZone: 'UTC' }).format(new Date(`${profile.joinedAt}T12:00:00Z`))}</span>}</div></div><button onClick={() => void save()} disabled={saving} className="flex h-10 items-center justify-center gap-2 rounded-xl bg-amber-400 px-5 text-sm font-bold text-slate-950 disabled:opacity-50"><Save className="size-4" />{saving ? 'Salvando…' : success ? 'Ficha salva' : 'Salvar ficha'}</button></div></div></section>
    <nav className="flex gap-1 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-2"><span className="rounded-xl bg-[#181818] px-4 py-2.5 text-sm font-bold text-white">Visão operacional</span><Link href="/briefings" className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-500 hover:bg-slate-50">Briefings</Link><Link href="/entradas" className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-500 hover:bg-slate-50">Entradas</Link><Link href="/trafego" className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-500 hover:bg-slate-50">Tráfego</Link></nav>
    <section className="grid gap-5 xl:grid-cols-[1.05fr_.95fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="flex items-center gap-2 font-bold"><UserRound className="size-5 text-amber-600" /> Responsáveis e operação</h3><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Gestores<input value={profile.managerNames.join(', ')} onChange={(event) => change({ managerNames: event.target.value.split(',').map((value) => value.trim()).filter(Boolean) })} className="mt-1.5 h-10 w-full rounded-xl border px-3 font-normal" placeholder="Marcelo, Gabriel" /></label><label className="text-sm font-semibold">Analista<input value={profile.analystName ?? ''} onChange={(event) => change({ analystName: event.target.value || null })} className="mt-1.5 h-10 w-full rounded-xl border px-3 font-normal" placeholder="Nome do analista" /></label><label className="text-sm font-semibold">Resultado<select value={profile.resultStatus} onChange={(event) => change({ resultStatus: event.target.value as ResultStatus })} className="mt-1.5 h-10 w-full rounded-xl border bg-white px-3 font-normal">{resultOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="text-sm font-semibold">Investimento diário (R$)<input type="number" min="0" step="0.01" value={profile.dailyBudgetCents == null ? '' : profile.dailyBudgetCents / 100} onChange={(event) => change({ dailyBudgetCents: event.target.value ? Math.round(Number(event.target.value) * 100) : null })} className="mt-1.5 h-10 w-full rounded-xl border px-3 font-normal" /></label></div><div className="mt-4"><p className="text-sm font-semibold">Anúncios e serviços ativos</p><div className="mt-2 flex flex-wrap gap-2">{platformOptions.map((platform) => { const active = profile.platforms.includes(platform.value); return <button key={platform.value} onClick={() => change({ platforms: active ? profile.platforms.filter((value) => value !== platform.value) : [...profile.platforms, platform.value] })} className={`rounded-xl border px-3 py-2 text-xs font-bold ${active ? 'border-amber-400 bg-amber-100 text-amber-900' : 'border-slate-200 text-slate-400'}`}>{platform.label}</button>; })}</div></div><label className="mt-4 block text-sm font-semibold">Link do formulário de entrada<input value={profile.intakeFormUrl ?? ''} onChange={(event) => change({ intakeFormUrl: event.target.value || null })} className="mt-1.5 h-10 w-full rounded-xl border px-3 font-normal" placeholder="https://..." /></label><label className="mt-4 block text-sm font-semibold">Observações<textarea value={profile.operationNotes ?? ''} onChange={(event) => change({ operationNotes: event.target.value })} rows={5} className="mt-1.5 w-full rounded-xl border p-3 font-normal" placeholder="Informações importantes sobre este cliente" /></label></div>
      <div className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="flex items-center gap-2 font-bold"><CalendarCheck2 className="size-5 text-amber-600" /> Últimas verificações</h3><p className="mt-1 text-sm text-slate-500">Controle rápido das frentes ativas deste cliente.</p><div className="mt-5 space-y-4">{([{ key: 'googleCheckedAt', label: 'Google' }, { key: 'metaCheckedAt', label: 'Meta' }, { key: 'socialCheckedAt', label: 'Social Media' }] as const).map((field) => <div key={field.key} className="rounded-xl border border-slate-200 p-4"><label className="text-sm font-bold">{field.label}<input type="date" value={profile[field.key] ?? ''} onChange={(event) => change({ [field.key]: event.target.value || null })} className="mt-2 h-10 w-full rounded-xl border border-slate-200 px-3 font-normal" /></label><button onClick={() => change({ [field.key]: new Date().toISOString().slice(0, 10) })} className="mt-2 text-xs font-bold text-amber-700">Marcar hoje</button></div>)}</div>{profile.intakeFormUrl && <a href={profile.intakeFormUrl} target="_blank" rel="noreferrer" className="mt-5 flex items-center justify-center gap-2 rounded-xl border border-slate-200 py-3 text-sm font-bold"><ExternalLink className="size-4" /> Abrir formulário de entrada</a>}</div></section>
  </div>;
}
