import { ArrowRight, CalendarDays, CheckCircle2, Clock3, FolderKanban, Gauge, LayoutGrid, MoreHorizontal, ShieldCheck, TrendingUp, UsersRound } from 'lucide-react';

const clients = [
  { slug: 'aurora-studio', name: 'Aurora Studio', sector: 'Arquitetura & interiores', initials: 'AS', projects: 4, tasks: 12, progress: 68, tone: 'from-amber-400 to-yellow-300' },
  { slug: 'nexo-tecnologia', name: 'Nexo Tecnologia', sector: 'SaaS B2B', initials: 'NT', projects: 3, tasks: 8, progress: 82, tone: 'from-sky-500 to-cyan-500' },
  { slug: 'casa-oliva', name: 'Casa Oliva', sector: 'Gastronomia', initials: 'CO', projects: 2, tasks: 7, progress: 54, tone: 'from-amber-500 to-orange-500' },
  { slug: 'verdejar', name: 'Verdejar', sector: 'Paisagismo', initials: 'VJ', projects: 3, tasks: 10, progress: 73, tone: 'from-emerald-500 to-teal-500' },
  { slug: 'lumina', name: 'Lumina', sector: 'Energia solar', initials: 'LU', projects: 2, tasks: 5, progress: 45, tone: 'from-rose-500 to-pink-500' },
  { slug: 'atlas-co', name: 'Atlas Co.', sector: 'Consultoria', initials: 'AC', projects: 1, tasks: 4, progress: 91, tone: 'from-slate-600 to-slate-800' },
];

export function ClientsView() {
  return <><div className="mb-4 flex flex-wrap gap-2"><FilterChip label="Todos" active /><FilterChip label="Ativos" count={24} /><FilterChip label="Pausados" count={3} /><FilterChip label="Encerrados" count={8} /></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{clients.map((client) => <a key={client.slug} href={`/clientes/${client.slug}`} className="group rounded-2xl border border-slate-200/80 bg-white p-5 transition hover:-translate-y-0.5 hover:border-amber-200 hover:shadow-lg hover:shadow-slate-200/50"><div className="flex items-start gap-3"><span className={`grid size-11 place-items-center rounded-xl bg-gradient-to-br text-xs font-bold text-white ${client.tone}`}>{client.initials}</span><span className="min-w-0 flex-1"><span className="block text-sm font-bold">{client.name}</span><span className="mt-0.5 block text-[11px] text-slate-400">{client.sector}</span></span><MoreHorizontal className="size-4 text-slate-400" /></div><div className="mt-5 grid grid-cols-2 gap-3"><Stat label="Projetos" value={client.projects} /><Stat label="Tarefas abertas" value={client.tasks} /></div><div className="mt-5"><div className="flex justify-between text-[10px] font-medium text-slate-400"><span>Progresso geral</span><span>{client.progress}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-amber-400" style={{ width: `${client.progress}%` }} /></div></div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4 text-[11px]"><span className="flex items-center gap-1.5 text-emerald-600"><span className="size-1.5 rounded-full bg-emerald-500" /> Ativo</span><span className="flex items-center gap-1 font-semibold text-amber-700 opacity-0 transition group-hover:opacity-100">Abrir workspace <ArrowRight className="size-3" /></span></div></a>)}</div></>;
}

const team = [
  { name: 'Marina Lima', role: 'Designer', dept: 'Design', initials: 'ML', doing: 'Campanha de primavera', client: 'Aurora Studio', open: 7, late: 1, load: 74, tone: 'bg-amber-100 text-amber-800' },
  { name: 'Rafael Souza', role: 'Web Designer', dept: 'Desenvolvimento', initials: 'RS', doing: 'Landing page — lançamento', client: 'Nexo Tecnologia', open: 5, late: 0, load: 58, tone: 'bg-sky-100 text-sky-700' },
  { name: 'João Costa', role: 'Gestor de Tráfego', dept: 'Performance', initials: 'JC', doing: 'Configuração Google Ads', client: 'Lumina', open: 8, late: 2, load: 82, tone: 'bg-amber-100 text-amber-700' },
  { name: 'Ana Martins', role: 'Social Media', dept: 'Conteúdo', initials: 'AM', doing: 'Calendário editorial', client: 'Verdejar', open: 6, late: 0, load: 63, tone: 'bg-emerald-100 text-emerald-700' },
];

export function TeamView() {
  return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{team.map((person) => <article key={person.name} className="rounded-2xl border border-slate-200/80 bg-white p-5"><div className="flex items-center gap-3"><span className={`grid size-11 place-items-center rounded-full text-xs font-bold ${person.tone}`}>{person.initials}</span><div><h2 className="text-sm font-bold">{person.name}</h2><p className="text-[10px] text-slate-400">{person.role} · {person.dept}</p></div></div><div className="mt-5 rounded-xl bg-slate-50 p-3"><p className="text-[9px] font-bold uppercase tracking-wider text-amber-700">Fazendo agora</p><p className="mt-1.5 text-xs font-semibold">{person.doing}</p><p className="mt-1 text-[10px] text-slate-400">{person.client}</p></div><div className="mt-4 flex justify-between text-[10px] text-slate-500"><span>{person.open} tarefas abertas</span><span className={person.late ? 'text-rose-500' : ''}>{person.late} atrasadas</span></div><div className="mt-2 h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-amber-400" style={{ width: `${person.load}%` }} /></div></article>)}</div>;
}

export function ProjectsView() {
  const projects = [{ name: 'Campanha de primavera', client: 'Aurora Studio', tasks: '8/12', due: '12 set', progress: 67, color: 'bg-amber-400' }, { name: 'Novo produto', client: 'Nexo Tecnologia', tasks: '14/17', due: '18 set', progress: 82, color: 'bg-sky-500' }, { name: 'Performance Q3', client: 'Casa Oliva', tasks: '7/13', due: '30 set', progress: 54, color: 'bg-amber-500' }, { name: 'Redes sociais', client: 'Verdejar', tasks: '11/15', due: 'Contínuo', progress: 73, color: 'bg-emerald-500' }];
  return <div className="grid gap-4 md:grid-cols-2">{projects.map((project) => <article key={project.name} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold text-amber-700">{project.client}</p><h2 className="mt-1 text-base font-bold">{project.name}</h2></div><span className={`grid size-9 place-items-center rounded-xl text-white ${project.color}`}><FolderKanban className="size-4" /></span></div><div className="mt-6 grid grid-cols-3 gap-3"><Stat label="Concluídas" value={project.tasks} /><Stat label="Prazo" value={project.due} compact /><Stat label="Progresso" value={`${project.progress}%`} compact /></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${project.color}`} style={{ width: `${project.progress}%` }} /></div></article>)}</div>;
}

export function CalendarView() {
  const days = Array.from({ length: 35 }, (_, index) => index - 1);
  const events: Record<number, { label: string; tone: string }[]> = { 1: [{ label: 'Campanha primavera', tone: 'bg-amber-100 text-amber-800' }, { label: 'Landing page', tone: 'bg-amber-100 text-amber-700' }], 3: [{ label: 'Criativos Meta', tone: 'bg-rose-100 text-rose-700' }], 4: [{ label: 'Calendário editorial', tone: 'bg-sky-100 text-sky-700' }], 8: [{ label: 'Revisão semanal', tone: 'bg-emerald-100 text-emerald-700' }], 12: [{ label: 'Entrega campanha', tone: 'bg-amber-100 text-amber-800' }] };
  return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="text-sm font-bold">Setembro 2026</h2><p className="text-[10px] text-slate-400">22 prazos neste mês</p></div><div className="flex rounded-lg bg-slate-100 p-1"><button className="rounded-md bg-white px-3 py-1.5 text-[10px] font-semibold shadow-sm">Mês</button><button className="px-3 py-1.5 text-[10px] font-semibold text-slate-400">Semana</button><button className="px-3 py-1.5 text-[10px] font-semibold text-slate-400">Dia</button></div></div><div className="grid grid-cols-7 border-b bg-slate-50 text-center text-[9px] font-bold uppercase tracking-wider text-slate-400">{['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'].map((day) => <span key={day} className="py-3">{day}</span>)}</div><div className="grid grid-cols-7">{days.map((day, index) => <div key={index} className={`min-h-28 border-b border-r p-2 ${day < 1 ? 'bg-slate-50/70 text-slate-300' : ''}`}><span className={`grid size-6 place-items-center rounded-full text-[10px] font-semibold ${day === 1 ? 'bg-amber-400 text-slate-950' : ''}`}>{day < 1 ? 30 + day : day}</span><div className="mt-1 space-y-1">{(events[day] || []).map((event) => <div key={event.label} className={`truncate rounded px-1.5 py-1 text-[9px] font-semibold ${event.tone}`}>{event.label}</div>)}</div></div>)}</div></div>;
}

export function ReportsView() {
  const bars = [44, 61, 53, 72, 68, 84, 77, 91, 73, 88, 96, 82];
  return <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><ReportMetric icon={CheckCircle2} label="Concluídas" value="184" note="+18% no período" tone="text-emerald-600 bg-emerald-50" /><ReportMetric icon={Clock3} label="Tempo médio" value="2,4 dias" note="-8h vs. agosto" tone="text-sky-600 bg-sky-50" /><ReportMetric icon={Gauge} label="No prazo" value="91%" note="Meta: 90%" tone="text-amber-700 bg-amber-50" /><ReportMetric icon={TrendingUp} label="Alterações" value="1,3" note="média por tarefa" tone="text-amber-600 bg-amber-50" /></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.4fr_.8fr]"><article className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-bold">Tarefas concluídas</h2><p className="text-[10px] text-slate-400">Últimos 12 meses</p><div className="mt-8 flex h-56 items-end gap-3">{bars.map((bar, index) => <div key={index} className="group relative flex-1 rounded-t-lg bg-amber-100 hover:bg-amber-400" style={{ height: `${bar}%` }}><span className="absolute -top-6 left-1/2 hidden -translate-x-1/2 text-[9px] font-bold group-hover:block">{bar}</span></div>)}</div><div className="mt-3 flex justify-between text-[9px] text-slate-400"><span>Out</span><span>Jan</span><span>Abr</span><span>Jul</span><span>Set</span></div></article><article className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-bold">Por departamento</h2><p className="text-[10px] text-slate-400">Volume concluído</p><div className="mt-6 space-y-5">{[['Design', 76, 'bg-amber-400'], ['Conteúdo', 62, 'bg-sky-500'], ['Tráfego', 54, 'bg-amber-500'], ['Web', 68, 'bg-emerald-500']].map(([name, value, color]) => <div key={String(name)}><div className="flex justify-between text-[11px] font-semibold"><span>{name}</span><span>{value}</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className={`h-full rounded-full ${color}`} style={{ width: `${value}%` }} /></div></div>)}</div></article></div></>;
}

export function AdminView() {
  const items = [{ icon: UsersRound, title: 'Usuários', detail: '12 usuários ativos', href: '#' }, { icon: ShieldCheck, title: 'Funções e permissões', detail: '6 funções · 34 permissões', href: '#' }, { icon: LayoutGrid, title: 'Departamentos', detail: '5 departamentos', href: '#' }, { icon: Gauge, title: 'Status e prioridades', detail: '10 status · 4 prioridades', href: '#' }, { icon: FolderKanban, title: 'Tipos de tarefa', detail: '14 tipos configurados', href: '#' }, { icon: CalendarDays, title: 'Campos personalizados', detail: '8 campos ativos', href: '#' }];
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map(({ icon: Icon, title, detail }) => <button key={title} className="group flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5 text-left transition hover:border-amber-200 hover:shadow-md"><span className="grid size-11 place-items-center rounded-xl bg-amber-50 text-amber-700"><Icon className="size-5" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-bold">{title}</span><span className="mt-1 block text-[11px] text-slate-400">{detail}</span></span><ArrowRight className="size-4 text-slate-300 transition group-hover:translate-x-1 group-hover:text-amber-500" /></button>)}</div>;
}

function FilterChip({ label, count, active }: { label: string; count?: number; active?: boolean }) { return <button className={`rounded-xl border px-3 py-2 text-xs font-semibold ${active ? 'border-amber-200 bg-amber-50 text-amber-800' : 'border-slate-200 bg-white text-slate-500'}`}>{label}{count !== undefined && <span className="ml-2 text-[10px] text-slate-400">{count}</span>}</button>; }
function Stat({ label, value, compact }: { label: string; value: string | number; compact?: boolean }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className={`mt-1 font-bold ${compact ? 'text-xs' : 'text-lg'}`}>{value}</p></div>; }
function ReportMetric({ icon: Icon, label, value, note, tone }: { icon: typeof CheckCircle2; label: string; value: string; note: string; tone: string }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5"><div className={`grid size-9 place-items-center rounded-xl ${tone}`}><Icon className="size-4" /></div><p className="mt-4 text-[10px] font-semibold text-slate-400">{label}</p><p className="mt-1 text-2xl font-bold tracking-tight">{value}</p><p className="mt-1 text-[10px] text-slate-400">{note}</p></article>; }
