'use client';

import { useEffect, useState } from 'react';
import { BriefcaseBusiness, CircleAlert, Plus } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { departmentOptions, type DepartmentKey } from '@/lib/work-entry';

type Service = { id: string; name: string; description: string | null; departmentKey: DepartmentKey; active: boolean };

export function ServicesView() {
  const [items, setItems] = useState<Service[]>([]);
  const [open, setOpen] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  useEffect(() => { void (async () => { const response = await fetch('/api/services'); const body = await response.json() as { data?: Service[]; error?: string }; if (response.ok) setItems(body.data ?? []); else setError(body.error ?? 'Não foi possível carregar os serviços.'); setLoading(false); if (new URLSearchParams(location.search).get('novo') === '1') setOpen(true); })(); }, []);
  async function create(form: FormData) { setError(''); const response = await fetch('/api/services', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(Object.fromEntries(form)) }); const body = await response.json() as { data?: Service; error?: string }; if (!response.ok) setError(body.error ?? 'Não foi possível cadastrar o serviço.'); else if (body.data) { setItems((current) => [...current, body.data!].sort((a, b) => a.name.localeCompare(b.name))); setOpen(false); history.replaceState(null, '', '/servicos'); } }
  return <>{error && <div className="mb-4 flex items-center gap-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700"><CircleAlert className="size-4" />{error}</div>}<div className="mb-4 flex justify-end"><button onClick={() => setOpen(true)} className="flex h-10 items-center gap-2 rounded-xl bg-amber-400 px-4 text-sm font-bold text-slate-950"><Plus className="size-4" /> Novo serviço</button></div>{loading ? <div className="rounded-2xl border bg-white p-8 text-center text-sm text-slate-500">Carregando serviços…</div> : items.length === 0 ? <div className="rounded-2xl border border-dashed bg-white p-10 text-center"><BriefcaseBusiness className="mx-auto size-8 text-amber-500" /><h2 className="mt-3 font-bold">Nenhum serviço cadastrado</h2></div> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between gap-3"><span className="grid size-10 place-items-center rounded-xl bg-amber-100 text-amber-800"><BriefcaseBusiness className="size-5" /></span><span className="rounded-lg bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">{departmentOptions.find((option) => option.key === item.departmentKey)?.label}</span></div><h2 className="mt-4 text-base font-bold">{item.name}</h2><p className="mt-1 text-sm text-slate-500">{item.description || 'Sem descrição.'}</p></article>)}</div>}<Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Novo serviço</DialogTitle><DialogDescription>Cadastre um serviço e defina o setor responsável.</DialogDescription></DialogHeader><form onSubmit={(event) => { event.preventDefault(); void create(new FormData(event.currentTarget)); }} className="space-y-4"><label className="block text-sm font-semibold">Nome<input name="name" required minLength={2} className="mt-1.5 h-10 w-full rounded-xl border px-3 font-normal" /></label><label className="block text-sm font-semibold">Setor<select name="departmentKey" className="mt-1.5 h-10 w-full rounded-xl border bg-white px-3 font-normal">{departmentOptions.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label><label className="block text-sm font-semibold">Descrição<textarea name="description" rows={4} className="mt-1.5 w-full rounded-xl border p-3 font-normal" /></label><DialogFooter><button type="button" onClick={() => setOpen(false)} className="h-10 rounded-xl border px-4 text-sm font-semibold">Cancelar</button><button type="submit" className="h-10 rounded-xl bg-amber-400 px-4 text-sm font-bold text-slate-950">Cadastrar</button></DialogFooter></form></DialogContent></Dialog></>;
}
