import { LockKeyhole, ShieldCheck } from 'lucide-react';
import Image from 'next/image';

export default async function LoginPage({
  searchParams,
}: {
  searchParams: Promise<{ return_to?: string }>;
}) {
  const { return_to } = await searchParams;
  const retryHref = return_to && return_to.startsWith('/') && !return_to.startsWith('//') ? return_to : '/';

  return <main className="grid min-h-screen bg-[#f6f7fb] lg:grid-cols-[1.05fr_.95fr]"><section className="hidden overflow-hidden bg-[#111111] p-12 text-white lg:flex lg:flex-col"><div className="flex items-center gap-3"><Image src="/mrc-logo.png" alt="Logo do Grupo MRC Digital" width={48} height={48} className="size-12 rounded-xl object-cover shadow-lg shadow-black/20" /><span><strong className="block">Grupo MRC</strong><span className="block text-[10px] uppercase tracking-[.18em] text-amber-300">Digital</span></span></div><div className="my-auto max-w-xl"><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-300">Toda a agência em movimento</p><h1 className="mt-4 text-5xl font-bold leading-[1.05] tracking-tight">Clareza para produzir.<br />Ritmo para crescer.</h1><p className="mt-6 max-w-lg text-base leading-relaxed text-slate-400">Clientes, projetos, briefings, produção e aprovações em um fluxo que toda a equipe entende.</p></div><p className="text-[10px] text-slate-500">Acesso restrito à equipe autorizada.</p></section><section className="flex items-center justify-center p-6"><div className="w-full max-w-sm"><div className="mb-8 lg:hidden"><Image src="/mrc-logo.png" alt="Logo do Grupo MRC Digital" width={64} height={64} className="size-16 rounded-2xl object-cover shadow-lg shadow-amber-200" /></div><p className="text-xs font-bold uppercase tracking-[.12em] text-amber-700">Acesso não confirmado</p><h2 className="mt-2 text-3xl font-bold tracking-tight">Verificando sua sessão</h2><p className="mt-2 text-sm leading-relaxed text-slate-500">O acesso a este workspace é controlado pelo Cloudflare Access. Se você chegou até aqui, o Access ainda não confirmou sua identidade para esta conta — tente novamente ou fale com o administrador do workspace.</p><a href={retryHref} className="mt-8 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-amber-400 text-sm font-semibold text-slate-950 shadow-lg shadow-amber-200 transition hover:bg-amber-300">Tentar novamente</a><div className="mt-6 space-y-3 rounded-2xl border border-slate-200 bg-white p-4"><p className="flex items-center gap-2 text-xs font-semibold"><ShieldCheck className="size-4 text-emerald-500" /> Sessão protegida pelo Cloudflare Access</p><p className="flex items-center gap-2 text-xs font-semibold"><LockKeyhole className="size-4 text-amber-500" /> Permissões verificadas no servidor</p></div><p className="mt-6 text-center text-[10px] leading-relaxed text-slate-400">Ao entrar, você concorda com as políticas internas de uso e segurança da agência.</p></div></section></main>;
}
